### ISSUE TITLE
is it possible running on Mac OS with xquartz?

### ISSUE THREAD

**Issue by zjsjack** [bzier/gym-mupen64plus#15]
I've tried to run the test on Mac OS but failed with the blew error:
f45c89c335f7:gym-mupen64plus zhangjs$ python ./test.py 
[2017-06-08 14:42:59,496] Making new env: Mario-Kart-Luigi-Raceway-v0
('ControllerHTTPServer started on port ', 8082)
initial_disp: /private/tmp/com.apple.launchd.BE9zLpGjMp/org.macosforge.xquartz:0
Starting emulator with comand: ['/Users/zhangjs/Downloads/mupen64plus-bundle-osx64-2.5/mupen64plus.app/Contents/MacOS/mupen64plus', '--corelib', '/Users/zhangjs/Downloads/mupen64plus-bundle-osx64-2.5/mupen64plus.app/Contents/MacOS/libmupen64plus.dylib', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/Users/zhangjs/Downloads/mupen64plus-bundle-osx64-2.5/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Calling wx.App() with DISPLAY: /private/tmp/com.apple.launchd.BE9zLpGjMp/org.macosforge.xquartz:0
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console Error: dlopen('./libmupen64plus.dylib') failed: dlopen(./libmupen64plus.dylib, 2): image not found
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library
2017-06-08 14:42:59.643 Python[62911:699335] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/k5/6933ktg504j586906rr7b8k88ms4cf/T/org.python.python.savedState
Changed DISPLAY to: /private/tmp/com.apple.launchd.BE9zLpGjMp/org.macosforge.xquartz:0
Emulator closed with code: 2
('Frame ', '10', ': ', '[0, 0, 1, 0, 0]')

Not sure is it doable on Mac OS?

**Comment by bzier** [comment]
Hey @zjsjack,
Unfortunately I don't have a Mac to test, so I'm not sure. I'll try to take a closer look at the error you're getting in the next couple days and see if I can come up with any suggestions.

**Comment by bzier** [comment]
I know this issue is nearing 4 years old now, but want to add a note before closing it. A couple things to mention which have changed since this was opened:
* The project no longer uses `wxPython` for screenshots; this was replaced with `mss`
* The project has been containerized using Docker, which handles all the dependencies

While it may be possible to run this on MacOS with XQuartz, it may involve making some changes to support. With the Docker  container, this runs fine on MacOS (no need for XQuartz), and I'm only planning to support the Docker setup at this point, so my recommendation to anyone who comes across this issue is to run that way instead. Closing this issue to clean up :)
