### ISSUE TITLE
Default the ROM path

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#6]
Provide a legitimate default ROM path so that configuration isn't required, but still available. The ROM path could be at the top-level directory of `gym-mupen64plus` and the directory could be included in git as well so that it is obvious where to put ROM files.

*Based on feedback [here](https://github.com/kevinhughes27/TensorKart/issues/12#issuecomment-287570128).*

**Comment by tanakataiki** [comment]
Hello, I managed to make file and I am trying to run mupen64
![screenshot from 2018-04-22 11-49-45](https://user-images.githubusercontent.com/37890520/39090805-57a2dcb2-4623-11e8-9ac8-29dbd57bbe10.png)

but I input command "mupen64plus"as tensorkart directory the terminal says no ROM file path.

I add ROMs(Mario Kart 64 (E) (V1.0) (Super W00ting Hack).z64 etc.. ) in ROMs directory that I corrected using my ninja skill.  
what I think is , Is the ROM name problem? Because it has Japanse, USA ,English version and name is a bit different.
Or another possible cause. 

Thanks.

**Comment by tanakataiki** [comment]
@bzier 
Yes, "mupen64plus /path/to/marioKartRom " is exactly what I wanted  to know.

![screenshot from 2018-04-23 10-42-36](https://user-images.githubusercontent.com/37890520/39102999-14db08a8-46e3-11e8-9b44-83122d2ec9f1.png)

but the ROM files are .z64 format and the example has .n64 format is this allocation error caused by ROM file? or I should subtract another ROMs in file?

Thanks

Thanks.

**Comment by bzier** [comment]
It looks like you just put the path itself. Sorry I should have been more clear. You need the full path including the filename. Example:
```
mupen64plus /path/to/marioKartRom/romFile.z64
```

I can't say for sure if there is a difference with the z64 file versus the n64 file.

**Comment by tanakataiki** [comment]
@bzier 
Thanks I finally managed to run.
