### ISSUE TITLE
Update to the latest mupen64plus-input-bot

### ISSUE THREAD

**Issue by kevinhughes27** [bzier/gym-mupen64plus#73]
The mupen64plus-input-bot plugin was updated to support multiple controllers in https://github.com/kevinhughes27/mupen64plus-input-bot/pull/8. As part of this change the way the controller server is accessed changed slightly - it now requires an integer at the end of the url to specify which controller.

Some of the code in the gym will need to change. e.g. [here](https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L212) and possibly some other places (check where that variable is used).

The Dockerfile can then be updated to use the latest sha for the input plugin https://github.com/bzier/gym-mupen64plus/blob/28de76ec4d9a9377dae80ff5853d11ddb69ee72b/Dockerfile#L34

related to #67

**Comment by roclark** [comment]
Hello again! I wanted to take a look at this as I have an interest in multi-agent environments down the line, but am stuck a bit. From what I understand, using the latest update to `mupen64plus-input-bot`, we now address controllers using integers for the path to specify controllers as you mentioned (ie. `localhost:8082/0` for controller 1, `localhost:8082/1` for controller 2, etc.). With that said, it sounds like we just need to append the controller number to the GET requests here and it will work.

I spent a decent amount of time over the weekend looking into this update, and believe I have an adequate solution to passing the controller index into the function where buttons get pressed, but I can't figure out a way to actually append the path to the request. From what I see, the request routes through the `_act()` function which calls `send_controls()` in the Controller class where the request is made.

https://github.com/bzier/gym-mupen64plus/blob/90a4a9401d32de5144ee0e5388705a8c8450b9f3/gym_mupen64plus/envs/mupen64plus_env.py#L411-L420

However, looking at `send_controls()`, I can't determine how the request is actually made. My original assumption was that I could update the path with a passed controller index to have that controller be used, but I don't see where that would be done. Is the request being made here or in a different section of code that I should be looking at?

I also looked at the code you linked to, but I wasn't sure what needs to change in that call, outside of using different ports for each controller server, but didn't feel that would take advantage of the updates to the input-bot. Is there an extra parameter or configuration that I should look into changing there that I am missing?

Thanks for any input! I feel like I'm fairly close, I just can't quite get over the hump of changing the path (assuming that's all that I actually need). On that note, one last reality check - once I get the request path update working, will everything "just work" from there? As in, assuming I make a request to hit the "A" button on `localhost:8082/1`, the second controller will input "A", and I don't need to make any further updates for that to work? I will obviously need to update any downstream models that use the gym to handle multiple inputs, but from this repository's perspective, is that it?

**Comment by kevinhughes27** [comment]
This looks like where we send the controller output: 

https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L445-L463

Look up the docs from `do_Get` to see how you can access more details of the request. 

I was initially thinking we should have a `server` per controller which is what I was suggesting in the issue. I am okay with your solution as well :smile:

**Comment by roclark** [comment]
Thanks for the quick response @kevinhughes27, I appreciate it! 😃 

That was also my assumption based on the name, but from what I've found, it looks like that is actually where the request is processed as opposed to sent if I am interpreting things correctly. I looked up the docs on the [SimpleHTTPRequestHandler](https://docs.python.org/2/library/simplehttpserver.html#SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET) (the code is using the `BaseHTTPRequestHandler`, which `SimpleHTTPRequestHandler` extends and contains the relevant documentation), and it looks like the `do_GET` method is where the incoming GET request gets handled and returns the relevant information based on the received request, but doesn't make the request. I could very well be misinterpreting this as I don't have as much experience with handling requests in this manner, but that's what I see.

If I am reading things correctly, I think I still need to track down where the request is made, but I can't quite figure that part out yet.

With all of that being said, I am perfectly fine with making separate servers per controller to solve the problem that way! It looks like @bzier's latest updates to the input-bot would allow us to specify different ports for the various controllers and update the config file so we don't have to change the path. But, again, I could be way off!

**Comment by kevinhughes27** [comment]
The request is made from the [input plugin](https://github.com/kevinhughes27/mupen64plus-input-bot) and received by the gym, the gym just needs to respond.

Specifically [here](https://github.com/kevinhughes27/mupen64plus-input-bot/pull/8/files#diff-4f568c7f1e7ac2acd1ec8e2c5d7f3c9eR80) is what I think you are looking for.

You are correct that the latest patch to the input plugin enables configuring an agent per port but if I understand the code correctly the controller index is still used even if the second agent is controller by a server on a different port [see the readme](https://github.com/kevinhughes27/mupen64plus-input-bot/pull/9/files#diff-04c6e90faac2675aa89e2176d2eec7d8R116) so an agent still needs to know which controller it is playing.

**Comment by bzier** [comment]
Hey @roclark, apologies in advance for the looonnngg response, but...

The `send_controls` mechanism is a little weird. I will try to answer your questions, and hopefully provide some clarification. [Here](https://github.com/bzier/gym-mupen64plus/blob/master/README.md#controllerhttpserver) is some documentation (admittedly a little lacking) in the readme about how the controller server works. (I may end up updating it based on this discussion to improve it)

Basically, as Kevin pointed out, the input plugin is running inside the emulator. It is what issues the HTTP GET request to the controller server. In our case here, the gym environment is acting as this server. As the emulator executes the game loop, it requests the controller state every step. The gym interface generally allows an agent to 'step' the environment. These two things both want to 'own' the environment and cause it to step. The code Kevin linked above ([here](https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L445-L463)) is where we receive and process the GET request (inside the gym env). It sleeps as long as the `hold_response` variable is true. Meanwhile, whenever an agent calls the step method, it ultimately calls `send_controls` which updates the controller state and sets `hold_response` to false (the code you reference earlier [here](https://github.com/bzier/gym-mupen64plus/blob/90a4a9401d32de5144ee0e5388705a8c8450b9f3/gym_mupen64plus/envs/mupen64plus_env.py#L411-L420)), freeing up the GET request processing to continue and return the controller data as a response back to the emulator. In effect, the emulator is waiting for the agent to step the gym environment. It is a bit weird, since the emulator is waiting for the response from gym, and the gym is waiting for the GET from the emulator, but that's how it works today.

It is worth mentioning here that I actually already kind of took care of this issue with PR #74 for docker-compose. I didn't remember at the time I opened it that there was already a separate issue for this work. The change does use the latest version of the input plugin; however, it does not do anything to work towards multi-agent support. I also realize now that I actually missed a part in my PR in configuring the plugin in a non-docker scenario (will try to fix it in the next few days). (A couple of the relevant parts [here](https://github.com/bzier/gym-mupen64plus/pull/74/files#diff-3254677a7917c6c01f55212f86c57fbfL32-R34) and [here](https://github.com/bzier/gym-mupen64plus/pull/74/files#diff-4e5e90c6228fd48698d074241c2ba760R40-R43) ... and the part I forgot to update [here](https://github.com/bzier/gym-mupen64plus/pull/74/files#diff-343f01d611812cf56824233f9730a521L250-L258))

---

Thinking about what you mentioned, and may be trying to do with the multi-agent support, I believe you will be able to able to do it with a few tweaks. For one, you need to make sure the emulator knows the controllers are 'plugged in'. This is handled through the configuration (even if you don't customize the host/port, you do need to set plugged=1). Also, the menu navigation for any given game may need to change to support additional controllers/players: like selecting a character, etc. 

Unfortunately, the gym interface does not currently support multi-agents either. There isn't really a standard way to deal with this. Recently I began exploring some alternatives, but I don't know what the best approach may be. The Ray project's RLlib is probably the best I've found so far (interesting [blog post](https://bair.berkeley.edu/blog/2018/12/12/rllib/) and the specific [section](https://bair.berkeley.edu/blog/2018/12/12/rllib/#multi-agent-environment-model) on their multi-agent environment model; and some [docs](https://ray.readthedocs.io/en/latest/rllib-examples.html)). I have only read on this, but haven't actually experimented with it at all yet. It is probably worth opening a completely separate issue for discussing how we want to address the multi-agent problem within this project.

---

@kevinhughes27, in response to your comment,
>if I understand the code correctly the controller index is still used even if the second agent is controller by a server on a different port see the readme so an agent still needs to know which controller it is playing

This isn't _exactly_ true. The plugin will always include the `/i` controller index in each request. However, if you configured different servers to handle each controller (e.g. on a different host or different port), they could each handle their GET requests independently, and completely ignore the request path with the index, and be oblivious to which controller they are 'holding'. In other words, the agent _**can**_ always know if it wants to, but doesn't _**need**_ to know if it doesn't care.

**Comment by roclark** [comment]
Thank you both for the very detailed answers! I misunderstood how the gym interacted with the input-bot and was confusing myself on how to go about this. So, it sounds like from here, @bzier's update in #74 would knock off this issue for updating to the latest version, and a new issue (possibly the existing #67?) should be created specifically for multi-agent support down the road. If that's the case, I will hold off on making updates to this specific issue, and focus on other items in the meantime. I will also do some reading on the multi-agent support to see if I can help out with that down the line too.

Thank you both again for the great responses and wonderful work here! I love this project and think there are some very exciting features in store in the future!

**Comment by bzier** [comment]
I think #67 is a perfect fit for discussing the multi agent problem. When I get the chance to apply the fix I mentioned above, I'll get my PR #74 merged and close this issue along with it.

**Comment by bzier** [comment]
Updated in #74. This can finally close!
